### ISSUE TITLE
Electron default app icon on 3.1.0

### ISSUE THREAD

**Issue by Krajsnick** [princejwesley/Mancy#140]
Hi!

The default Electron app icon is being used when downloading darwin x64 3.1.0.

The pink Mancy REPL icon worked before, in 3.0.0.

**Comment by princejwesley** [comment]
😱 Thats bad

**Comment by Krajsnick** [comment]
Yes it is! :) Because the icon that should be there is gorgeous!

**Comment by texastoland** [comment]
I miss the icon too 😰

**Comment by princejwesley** [comment]
Sorry for the delayed response.

Do this to fix the problem:
From `finder`, Open `Mancy.app > Show Package Content > Contents > Info.plist`
and update `electron.icns` to `atom.icns`
![image](https://cloud.githubusercontent.com/assets/1622515/18503517/e768ad0c-7a7a-11e6-9792-49a1ae69e86a.png)

Note: macOS caches the icons, copy the app to different folder after making the above change. remove the old one and move the new copy back to original path.

**Comment by BrandonSmith** [comment]
Another fix...

In `Finder` right click on `Mancy.app` and click `Get Info`. Now right click again on `Mancy.app > Show Package Contents > Contents > Resources`. Drag `atom.icns` to the file to the icon in the `Get Info` window. Icon changed at the OS level rather than modifying the `Info.plist`.

Screen record:
http://g.recordit.co/epuJI8XAjM.gif

**Comment by robahl** [comment]
Fixed in 3.2.0
