### ISSUE TITLE
app crashes on start with blank error message

### ISSUE THREAD

**Issue by devsnek** [princejwesley/Mancy#149]
![](https://i.imgur.com/Y43qHS1.png)

**Comment by princejwesley** [comment]
can you click copy & report button and paste here?

**Comment by GusCaplan** [comment]
it doesn't do anything, it's frozen @princejwesley

**Comment by princejwesley** [comment]
Environment details please

**Comment by GusCaplan** [comment]
#### Application Error
##### Message
undefined
##### Stack Trace
```js
undefined
```

#### System Details
 | …
------------ | -------------
**Platform** | darwin
**Arch** | x64
**Electron Version** | 1.2.6
**Mancy Version** | 3.1.0

as useless as this trace is, i thought i would post it anyway

**Comment by cjus** [comment]
I encountered this issue after changing my mancy config. I changed the Editor Mode from "Notebook" back to "REPL". The app appeared to exit. Then I couldn't seem to restart it. It turned out that the app was running in memory. After using `Activity Monitor` on Mac to kill the process I was then able to start it again.
