### ISSUE TITLE
Can't type Chinese! Sad.

### ISSUE THREAD

**Issue by jincdream** [princejwesley/Mancy#45]

**Comment by princejwesley** [comment]
@jincdream I don't know how to test it. I could able to type something using `Pinyin Simplified` keyboard layout.
![image](https://cloud.githubusercontent.com/assets/1622515/11024675/f192606e-86b7-11e5-903a-e744eaaff17d.png)

You can turn off auto complete`(Preferences...` > `Disable automatic auto complete`) if it hinders you.

I may need your help since I don't know which keyboard layout to set, what key combination to key for testing the REPL.

**Comment by jincdream** [comment]
After I input pinyin cannot choose words.

You can try type `lin`,but just 'n' is showed,and the selector is gone.

The normal situation is like this:
![k 73_u bkj0qu 6d22 6b3](https://cloud.githubusercontent.com/assets/4645261/11025492/90f43d4e-86d6-11e5-836d-57d22503b42f.jpg)


![399f0804-2ae1-49ee-ba3a-64515697d567](https://cloud.githubusercontent.com/assets/4645261/11025508/bd1d6e04-86d6-11e5-80b4-681d6fcc0fc3.png)

The normal situation in the Mancy:
type `l`,'l','command + i','command + n' hack `lin`

![wechat_1447041494](https://cloud.githubusercontent.com/assets/4645261/11025674/2d49482c-86d9-11e5-98e8-a19946cfdd31.jpeg)

I regret not learn English well :(

**Comment by princejwesley** [comment]
@jincdream Identified the issue. I'll fix and let you know

**Comment by jincdream** [comment]
ok,I am waiting.

**Comment by princejwesley** [comment]
@jincdream Can you try the latest code?

**Comment by jincdream** [comment]
node.js v5.0.0 or v0.12.7

**Comment by princejwesley** [comment]
@jincdream v4.1.2 or v5.0.0

**Comment by princejwesley** [comment]
![image](https://cloud.githubusercontent.com/assets/1622515/11027409/fae3e49e-86da-11e5-8c70-e6d2fdbdd476.png)

**Comment by jincdream** [comment]
I am installing~

**Comment by jincdream** [comment]
![wechat_1447054900](https://cloud.githubusercontent.com/assets/4645261/11028353/d969702c-86f8-11e5-9a58-da3ddfe18c23.jpeg)

Nice! It's fixed. thx~

by the way
林文滨是基佬。: )
